# SITE CONFIGURATION
baseurl: "/online.portfolio"
url: "https://leeeeesamo.github.io"

## THEME-SPECIFIC CONFIGURATION ##
title: My Career Portfolio
description: A professional portfolio showcasing my career achievements.                                       
avatar: assets/img/online-portfolio.png                 # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

## Header and footer text ##
header_text: Welcome to My Online Portfolio             
header_feature_image: assets/img/header/header_banner.jpg
header_feature_image_responsive: true
footer_text: >
  © Leesa Moore. All rights reserved. Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>. Designed with passion and professionalism. Let's connect: <a href="https://www.linkedin.com/in/leesa-moore/">LinkedIn</a> | <a href="mailto:lmoore0510@gmail.com">Email Me</a>

## Blog ##
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart_banner.jpg             # A bit transparent for color posts.

## Features ## 
## More in the _data folder for share buttons, author and language
## For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                           # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: G-62GQJMN2DP                          # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Navigation
navigation:
  - name: "Portfolio"
    link: "/portfolio/"
  - name: "Resumes"
    link: "/resumes/"
  - name: "Contact Me"
    link: "/contact/"

# PAGINATION
paginate: 5
paginate_path: "/portfolio/page:num" 

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name                         # Updated for better permalink structure
    sort_by: "date"                                     # Sort items by date (customize as needed)
    sort_order: "descending"

# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true
plugins:
  - jekyll-paginate                                     # Pagination plugin
  - jekyll-seo-tag                                      # SEO optimization plugin
  - jekyll-feed                                         # RSS feed plugin

exclude: 
  - ".jekyll-cache" 
  - ".jekyll-metadata" 
  - ".idea" 
  - "vendor/*" 
  - "assets/node_modules/*"
  - search.md
  
# theme: type-on-strap
remote_theme: sylhare/Type-on-Strap                    
